### ISSUE TITLE
how to install on unraid

### ISSUE THREAD

**Issue by reitenth** [Radiicall/jellyfin-rpc#20]
im trying to install the linux exe but im getting this atm

![image](https://user-images.githubusercontent.com/94771708/234114265-4f4f5be4-6440-4bda-b4eb-7e0040f185c9.png)

**Comment by reitenth** [comment]
is it possible to install via docker?

**Comment by AstralDestiny** [comment]
> is it possible to install via docker?

Via a container wouldn't be too hard, My only issue is I don't know rust very well and would prefer a dockerfile to build the entire project and then run the application in question, Vs just having a container that just pulls the prebuilt and runs it in a container.. But that's just me..

**Comment by Radiicall** [comment]
> im trying to install the linux exe but im getting this atm
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/94771708/234114265-4f4f5be4-6440-4bda-b4eb-7e0040f185c9.png)
> 
> 


If you look up your linux distro + libssl.so.3 you should be able to find out what package is needed

**Comment by reitenth** [comment]
the unraid guys says just to ask if it can be installed via docker as unraid doesnt like os level packages.

**Comment by Radiicall** [comment]
There is no official way to install through docker and you need discord running for it to work, but you could try to set it up yourself if you want

**Comment by reitenth** [comment]
i dont really know how to docker, but i can try.

**Comment by just5ky** [comment]
Wonder if we can use https://github.com/linuxserver/docker-baseimage-kasmvnc and add discord to it, run the RPC script in the background. Caveat would be you will be online in discord all the time I guess, and you will be logged out when the container updates.

**Comment by just5ky** [comment]
I am able to build an almost working container, the issue is discord app is crashing right now, need to fix that, otherwise its working
@reitenth 
https://github.com/just5ky/jelly_rpc

```yml
  jelly-rpc:
    image: justsky/jelly_rpc
    container_name: jelly_rpc
    #restart: unless-stopped
    ports:
      - 7777:7777
    volumes:
      - $DOCKERDIR/jelly_rpc/main.json:/config/.config/jellyfin-rpc/main.json:ro
    environment:
      - CUSTOM_PORT=7777
```
